apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: {{.Release.Namespace}}
spec:
  selector:
    app: api-gateway
  type: {{ .Values.service.type }}
  ports:
  - name: {{ .Values.service.portNames.apiGateway }}
    port: {{ .Values.service.ports.apiGateway }}
    targetPort: api-gateway-http
    protocol: TCP
    {{- if (eq .Values.service.type "ClusterIP") }}
    nodePort: null
    {{- else if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePorts.apiGateway)) }}
    nodePort: {{ .Values.service.nodePorts.apiGateway }}
    {{- end }}
  - name: {{ .Values.service.portNames.apiGatewayTls }}
    port: {{ .Values.service.ports.apiGatewayTls }}
    targetPort: api-gateway-https
    protocol: TCP
    {{- if (eq .Values.service.type "ClusterIP") }}
    nodePort: null
    {{- else if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePorts.apiGatewayTls)) }}
    nodePort: {{ .Values.service.nodePorts.apiGatewayTls }}
    {{- end }}
  - name: api-gateway-stats
    port: 9900
    targetPort: api-gateway-stats
    protocol: TCP