apiVersion: apps/v1
kind: Deployment
metadata:  
  name: api-gateway
  namespace: {{.Release.Namespace}}
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: envoyproxy/envoy:v1.25-latest
          imagePullPolicy: Always
          tty: true          
          env:
            - name: DEBUG_MODE
              value: "{{.Values.debugMode}}"
          command: ["/bin/bash", "-c"]
          args: 
            - /docker-entrypoint.sh
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy.yaml
              subPath: config.yml
            - name: envoy-config
              mountPath: /docker-entrypoint.sh
              subPath: init.sh
            - name: downstream-tls-certificate
              mountPath: /certs/downstream.crt
              subPath: tls.crt
            - name: downstream-tls-certificate
              mountPath: /certs/downstream.key
              subPath: tls.key
            - name: downstream-tls-certificate
              mountPath: /certs/downstream-ca.crt
              subPath: tls.crt
            - name: upstream-certificate
              mountPath: /certs/internal-ca.crt
              subPath: ca.crt
            - name: upstream-certificate
              mountPath: /certs/upstream.crt
              subPath: tls.crt
            - name: upstream-certificate
              mountPath: /certs/upstream.key
              subPath: tls.key
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 9900
      restartPolicy: Always
      volumes:
        - name: downstream-tls-certificate
          secret:
            secretName: {{ template "downstream.certSecret" . }}
        - name: upstream-certificate
          secret:
            secretName: api-gateway-upstream-cert
        - name: envoy-config
          configMap:  
            name: api-gateway-config
            defaultMode: 480 #this value MUST be set in decimal NOT in octal