apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: {{.Release.Namespace}}
spec:
  selector:
    app: api-gateway
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
    {{- if (eq .Values.service.type "ClusterIP") }}
    nodePort: null
    {{- else if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePorts.apiGateway)) }}
    nodePort: {{ .Values.service.nodePorts.apiGateway }}
    {{- end }}
  - name: https
    port: 443
    targetPort: https
    protocol: TCP
    {{- if (eq .Values.service.type "ClusterIP") }}
    nodePort: null
    {{- else if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePorts.apiGatewayTls)) }}
    nodePort: {{ .Values.service.nodePorts.apiGatewayTls }}
    {{- end }}
  - name: stats
    port: 9900
    targetPort: stats
    protocol: TCP