{{- if .Values.services.keycloak.enabled -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: auth-init
  namespace: {{.Release.Namespace}}
data:
  users-create-script.sh: |
    # apt-get update
    # apt-get install curl jq -y

    # Check if Auth is healthy
    export REALM=lms

    echo "Waiting Auth to launch on 8080..."
    until curl --silent --fail http://auth:8080/auth/health/ready | grep -q '"status": "UP"' ; do
      printf '.'
      sleep 1
    done
    echo "Auth is launched"

    
    /opt/keycloak/bin/kcadm.sh config credentials --server http://auth:8080/auth --realm master --user {{.Values.services.keycloak.adminCreds.username}} --password {{.Values.services.keycloak.adminCreds.password}}

    {{- range $user := .Values.services.keycloak.initUsers }}
    echo "Creating user '{{ $user.username }}'"
    /opt/keycloak/bin/kcadm.sh create users -s username={{ $user.username }} -s enabled=true -r $REALM
    echo "Setting password for user '{{ $user.username }}'"
    /opt/keycloak/bin/kcadm.sh set-password -r $REALM --username={{ $user.username }} --new-password {{ $user.password }}
      {{- range $role := $user.roles }}
      echo "Assigning role '{{ $role }}' password for user '{{ $user.username }}'"
    /opt/keycloak/bin/kcadm.sh add-roles --username {{ $user.username }} --rolename {{ $role }} -r $REALM
      {{- end }}
    {{- end }}    
{{- end -}}