{{- if .Values.services.keycloak.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: {{.Release.Namespace}}
spec:
  selector:
    app: auth
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
{{- end -}}