kind: ConfigMap
apiVersion: v1
metadata:
  name: aws-connector-config
  namespace: {{.Release.Namespace}}
data:
  config: |
    logs:
      level: "info"

    amqp:
      log_level: debug
      enabled: true
      protocol: amqp #amqp | amqps
      hostname: {{ .Values.amqp.hostname }}
      port: {{ .Values.amqp.port }}
      basic_auth:
        enabled: true
        username: {{ .Values.amqp.username }}
        password: {{ .Values.amqp.password }}
    
    dms_manager_client:
      log_level: debug
      auth_mode: noauth
      prtotocol: http
      hostname: dms-manager
      port: 8085
    
    device_manager_client:
      log_level: debug
      auth_mode: noauth
      prtotocol: http
      hostname: device-manager
      port: 8085
    
    ca_client:
      log_level: debug
      auth_mode: noauth
      prtotocol: http
      hostname: ca
      port: 8085
    
    connector_id:  {{ .Values.services.awsConnector.connectorID }}
    aws_config: 
      access_key_id: {{ .Values.services.awsConnector.credentials.accessKeyId }}
      secret_access_key:  {{ .Values.services.awsConnector.credentials.secretAccessKey }}
      region:  {{ .Values.services.awsConnector.credentials.region }}