apiVersion: apps/v1
kind: StatefulSet
metadata:  
  name: ca
  namespace: {{.Release.Namespace}}
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: ca
spec:
  replicas: 1
  serviceName: "ca"
  selector:
    matchLabels:
      app: ca
  template:
    metadata:
      labels:
        app: ca
    spec:
      containers:
        - name: ca
          image: {{ .Values.services.ca.image }}
          imagePullPolicy: Always
          tty: true         
          volumeMounts:
            - name: api-config
              mountPath: /etc/lamassuiot/config.yml
              subPath: config
            {{ if gt (len .Values.services.ca.engines.golang) 0 }}
            - name: golang-engine-storage
              mountPath: /data
            {{ end }}
          ports:
            - containerPort: 8085
      restartPolicy: Always
      volumes:
        - name: api-config
          configMap:  
            name: ca-config
  volumeClaimTemplates:
  {{ if gt (len .Values.services.ca.engines.golang) 0 }}
  - metadata:
      name: golang-engine-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: null
      resources:
        requests:
          storage: 1Gi
  {{end}}
