apiVersion: apps/v1
kind: Deployment
metadata:  
  name: ca
  namespace: {{.Release.Namespace}}
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: ca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ca
  template:
    metadata:
      labels:
        app: ca
    spec:
      containers:
        - name: ca
          image: {{ .Values.services.ca.image }}
          imagePullPolicy: Always
          tty: true         
          volumeMounts:
            - name: api-config
              mountPath: /etc/lamassuiot/config.yml
              subPath: config
          ports:
            - containerPort: 8085
      restartPolicy: Always
      volumes:
        - name: api-config
          configMap:  
            name: ca-config

