apiVersion: v1
kind: Service
metadata:
  name: cloud-proxy
  namespace: {{.Release.Namespace}}
spec:
  selector:
    app: cloud-proxy
  type: ClusterIP
  ports:
  - name: https
    port: 8085
    targetPort: 8085
    protocol: TCP