apiVersion: apps/v1
kind: Deployment
metadata:  
  name: dms-manager
  namespace: {{.Release.Namespace}}
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: dms-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dms-manager
  template:
    metadata:
      labels:
        app: dms-manager
    spec:     
      containers:
        - name: dms-manager
          image: {{.Values.services.dmsManager.image}}
          imagePullPolicy: Always
          tty: true          
          env:
            - name: LAMASSU_DEVICE_MANAGER_ADDRESS
              value: device-manager:8085
            - name: SERVICE_NAME
              value: dmsManager
            - name: DEBUG_MODE
              value: "{{.Values.debugMode}}"
            - name: PORT
              value: "8085"
            - name: PROTOCOL
              value: https
            - name: CERT_FILE
              value: /certs/tls.crt
            - name: KEY_FILE
              value: /certs/tls.key
            - name: MUTUAL_TLS_ENABLED
              value: "true"
            - name: MUTUAL_TLS_CLIENT_CA
              value: /certs/internal-ca.crt
            - name: AMQP_SERVER_USE_BASIC_AUTH
              value: "true"
            - name: AMQP_SERVER_USERNAME
              value: "{{.Values.rabbitmq.auth.username}}"
            - name: AMQP_SERVER_PASSWORD
              value: "{{.Values.rabbitmq.auth.password}}"
            - name: AMQP_SERVER_ENABLE_TLS
              value: "true"
            - name: AMQP_SERVER_HOST
              value: rabbitmq
            - name: AMQP_SERVER_PORT
              value: "5671"
            - name: AMQP_SERVER_CA_CERT
              value: /certs/internal-ca.crt

            - name: POSTGRES_HOSTNAME
              value: {{ include "postgres.hostname" . }}
            - name: POSTGRES_PORT
              value: "{{ include "postgres.port" . }}"
            - name: POSTGRES_DATABASE
              value: dmsmanager
            - name: POSTGRES_USERNAME
              value: {{ include "postgres.username" . }}
            - name: POSTGRES_PASSWORD
              value: {{ include "postgres.password" . }}  
            - name: LAMASSU_CA_ADDRESS
              value: https://ca:8085
            - name: LAMASSU_CA_CERT_FILE
              value: /certs/internal-ca.crt
            - name: DOWNSTREAM_CERT
              value: /certs/downstream.crt
            - name: DOWNSTREAM_CA_CERT
              value: /certs/downstream.crt
          volumeMounts:
            - name: tls-certificates
              mountPath: /certs/tls.crt
              subPath: tls.crt
            - name: tls-certificates
              mountPath: /certs/tls.key
              subPath: tls.key
            - name: tls-certificates
              mountPath: /certs/internal-ca.crt
              subPath: ca.crt
            - name: downstream-tls-certificates
              mountPath: /certs/downstream.crt
              subPath: tls.crt
          ports:
            - containerPort: 8085
      restartPolicy: Always
      volumes:
        - name: tls-certificates
          secret:
            secretName: dms-manager-upstream-cert
        - name: downstream-tls-certificates
          secret:
            secretName: downstream-cert