apiVersion: apps/v1
kind: Deployment
metadata:  
  name: dms-manager
  namespace: {{.Release.Namespace}}
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: dms-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dms-manager
  template:
    metadata:
      labels:
        app: dms-manager
    spec:
      containers:
        - name: dms-manager
          image: {{ .Values.services.dmsManager.image }}
          imagePullPolicy: Always
          tty: true         
          volumeMounts:
            - name: api-config
              mountPath: /etc/lamassuiot/config.yml
              subPath: config
            - name: downstream-tls-certificate
              mountPath: /certs/downstream-ca.crt
              subPath: tls.crt
          ports:
            - containerPort: 8085
      restartPolicy: Always
      volumes:
        - name: api-config
          configMap:  
            name: dms-manager-config
        - name: downstream-tls-certificate
          secret:
            secretName:  {{ ternary .Values.tls.externalOptions.secretName  "downstream-cert" (eq .Values.tls.type "external") }}
        