apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: downstream-tls-certificate
  namespace: {{.Release.Namespace}}
spec:
  isCA: false
  commonName: {{.Values.domain}}
  duration: {{.Values.tls.letsEncryptOptions.selfSignedOptions.duration}}
  dnsNames:
    - "{{.Values.domain}}"
  secretName: downstream-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    {{ if ne .Values.tls.letsEncryptOptions.clusterIssuer "" }}
    kind: ClusterIssuer
    name: {{ .Values.tls.letsEncryptOptions.clusterIssuer }}
    {{ else }}
    kind: Issuer
    name:  {{ ternary .Values.tls.letsEncryptOptions.issuer "downstream-ca-selfsigned-issuer" (ne .Values.tls.letsEncryptOptions.issuer "") }} 
    {{ end }}
    group: cert-manager.io