{{- if .Values.integratedPostgres.enabled -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: postgres-ha-init
  namespace: {{.Release.Namespace}}
data:
  init.sql: |
    CREATE DATABASE auth;
    CREATE DATABASE alerts;
    CREATE DATABASE ca;
    CREATE DATABASE cloudproxy;
    CREATE DATABASE devicemanager;
    CREATE DATABASE dmsmanager;
{{- end -}}