apiVersion: apps/v1
kind: Deployment
metadata:  
  name: ui
  namespace: {{.Release.Namespace}}
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:     
      containers:
        - name: ui
          image: {{.Values.services.ui.image}}
          imagePullPolicy: {{ .Values.global.imagePullPolicy | quote }}
          env:
            - name: CHART_VERSION
              value: {{.Chart.Version}}
            - name: HELM_REVISION
              value: "{{.Release.Revision}}"
            - name: DOMAIN
              value: "${window.location.host}"
            - name: OIDC_AUTHORITY
              value: {{.Values.auth.oidc.frontend.authority}}
            - name: OIDC_CLIENT_ID
              value: {{.Values.auth.oidc.frontend.clientId}}
            - name: COGNITO_ENABLED
              value: "{{.Values.auth.oidc.frontend.awsCognito.enabled}}"
            - name: COGNITO_HOSTED_UI_DOMAIN
              value: {{.Values.auth.oidc.frontend.awsCognito.hostedUiDomain}}
            - name: CLOUD_CONNECTORS
              value: "[ \"{{.Values.services.awsConnector.connectorID }}\" ]"
          ports:
            - containerPort: 8080
      restartPolicy: Always