apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: {{.Release.Namespace}}
spec:
  selector:
    app: ui
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP