apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-upstream-ca-cert
  namespace: {{.Release.Namespace}}
spec:
  isCA: true
  duration: {{.Values.tls.duration}}
  commonName: internal-lamassu-ca
  secretName: root-upstream-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
