apiVersion: apps/v1
kind: Deployment
metadata:  
  name: va
  namespace: {{.Release.Namespace}}
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: va
spec:
  replicas: 1
  selector:
    matchLabels:
      app: va
  template:
    metadata:
      labels:
        app: va
    spec:     
      containers:
        - name: va
          image: {{.Values.services.va.image}}
          imagePullPolicy: {{ .Values.global.imagePullPolicy | quote }}
          tty: true          
          volumeMounts:
            - name: api-config
              mountPath: /etc/lamassuiot/config.yml
              subPath: config
          ports:
            - containerPort: 8085
      restartPolicy: Always
      volumes:
        - name: api-config
          configMap:  
            name: va-config

