apiVersion: v1
kind: Service
metadata:
  name: va
  namespace: {{.Release.Namespace}}
spec:
  selector:
    app: va
  type: ClusterIP
  ports:
  - name: http
    port: 8085
    targetPort: 8085
    protocol: TCP