{{- if .Values.vault.global.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-cert
  namespace: {{.Release.Namespace}}
spec:
  isCA: false
  commonName: vault*
  duration: {{.Values.tls.duration}}
  dnsNames:
    - "vault-active"
    - "vault"
    - "vault*"
  secretName: vault-upstream-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: upstream-ca-issuer
    kind: Issuer
    group: cert-manager.io
{{- end -}}
