domain: dev.lamassu.io
storageClassName: &storage-class-name "" # <----  Default Value

services:
  apiGateway:
    image: lamassuiot/lamassu-gateway:v1.0.12
    debugMode: false
  keycloak:
    image: lamassuiot/lamassu-auth:v1.0.12
    username: admin
    password: admin
  ui:
    image: lamassuiot/lamassu-ui:v0.0.14
  ca:
    image: lamassuiot/lamassu-ca:v1.0.18
  deviceManager:
    image: lamassuiot/lamassu-device-manager:v0.0.9
    minimumReenrollmentDays: 30
  dmsManager:
    image: lamassuiot/lamassu-dms-enroller:v0.0.23
  database:
    image: lamassuiot/lamassu-db:v1.0.12
    username: admin
    password: admin
  openPolicyAgent:
    image: openpolicyagent/opa:0.37.1-envoy
  cloudProxy:
    image: lamassuiot/lamassu-cloud-proxy:v0.0.1
  rabbitmq:
    image: lamassuiot/lamassu-rabbitmq:v1.0.12
  jaeger:
    image: jaegertracing/all-in-one:1.30.0

# Consul values must be set on another section to be read by the subchart
consul:
  global:
    datacenter: lamassu-k8s
  server:
    replicas: 3
    storageClassName: *storage-class-name

vault:
  server:
    affinity: ""
    extraVolumes:
    - type: secret
      name: vault-upstream-cert
    ha:
      enabled: true
      replicas: 5
      config: |
        ui = true
        listener "tcp" {
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_cert_file = "/vault/userconfig/vault-server-tls/tls.crt"
          tls_key_file  = "/vault/userconfig/vault-server-tls/tls.key"
          tls_client_ca_file = "/vault/userconfig/vault-server-tls/ca.crt"
        }

  ui:
    enabled: true
    serviceType: "NodePort"
    serviceNodePort: 30100
  injector:
    enabled: false
