apiVersion: v1
kind: Service
metadata:
  name: {{ include "soft.fullname" . }}
spec:
  type: ClusterIP
  ports:
  - port: 5657
    targetPort: 5657
    protocol: TCP
    name: "tcp-pkcs11"
  selector:
    app: {{ include "soft.fullname" . }}