apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: {{.Release.Namespace}}
spec:
  selector:
    app: auth
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 8443
    targetPort: 8443
    protocol: TCP