apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-cert
  namespace: {{.Release.Namespace}}
spec:
  isCA: false
  commonName: ca*
  dnsNames:
    - "ca"
    - "ca*"
  secretName: ca-upstream-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: upstream-ca-issuer
    kind: Issuer
    group: cert-manager.io