apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: downstream-ca-issuer
  namespace: {{.Release.Namespace}}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-downstream-ca-cert
  namespace: {{.Release.Namespace}}
spec:
  isCA: true
  commonName: selfsigned-downstream-ca
  secretName: root-downstream-ca-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: downstream-ca-issuer
    kind: Issuer
    group: cert-manager.io