apiVersion: v1
kind: Service
metadata:
  name: opa-server
  namespace: {{.Release.Namespace}}
spec:
  selector:
    app: opa-server
  type: ClusterIP
  ports:
  - name: opa
    port: 9191
    targetPort: 9191
  - name: https
    port: 8181
    targetPort: 8181
    protocol: TCP
