apiVersion: apps/v1
kind: Deployment
metadata:  
  name: opa-server
  namespace: {{.Release.Namespace}}
  labels:
    app: opa-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa-server
  template:
    metadata:
      labels:
        app: opa-server
    spec:
      containers:
        - name: opa-server
          image: {{.Values.services.openPolicyAgent.image}}
          volumeMounts:
            - name: opa-server-policy-config
              mountPath: /opa/policy.rego
              subPath: policy.rego
            - name: opa-server-config-config
              mountPath: /opa/config.yaml
              subPath: config.yaml
          ports:
            - containerPort: 9191
            - containerPort: 8181
          args:
            - run
            - --server
            - --addr=0.0.0.0:8181
            - --config-file=/opa/config.yaml
            - --log-level=info
            - --log-format=text
            - --ignore=.*
            - /opa/policy.rego
      restartPolicy: Always
      volumes:
        - name: opa-server-policy-config
          configMap:  
            name: opa-server-policy-cm
        - name: opa-server-config-config
          configMap:  
            name: opa-server-config-cm
