apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rabbitmq-cert
  namespace: {{.Release.Namespace}}
spec:
  isCA: false
  commonName: rabbitmq*
  dnsNames:
    - "rabbitmq"
    - "rabbitmq*"
  secretName: rabbitmq-upstream-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: upstream-ca-issuer
    kind: Issuer
    group: cert-manager.io