apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: upstream-ca-issuer
  namespace: {{.Release.Namespace}}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-upstream-ca-cert
  namespace: {{.Release.Namespace}}
spec:
  isCA: true
  commonName: internal-lamassu-ca
  secretName: root-upstream-ca-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: upstream-ca-issuer
    kind: Issuer
    group: cert-manager.io
