apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-cert
  namespace: {{.Release.Namespace}}
spec:
  isCA: false
  commonName: vault*
  dnsNames:
    - "vault"
    - "vault*"
  secretName: vault-cert-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: lamassu-ca-issuer
    kind: Issuer
    group: cert-manager.io
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: vault-cm
  namespace: {{.Release.Namespace}}
data:
  config.json: |
    {
      "ui": true,
      "listener": {
          "tcp": {
              "address": "0.0.0.0:8200",
              "tls_cert_file": "/vault/tls/tls.crt",
              "tls_key_file": "/vault/tls/tls.key"
          }
      },
      "storage": {
          "consul": {
              "address": "https://consul:8501",
              "path": "vault",
              "tls_ca_file": "/vault/tls/consul.crt"
          }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-deployment
  namespace: {{.Release.Namespace}}
  labels:
    app: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: {{.Values.image.vault}}
          volumeMounts:
            - name: vault-json-config
              mountPath: /vault/config/config.json
              subPath: config.json
            - name: vault-tls-certificates
              mountPath: /vault/tls/consul.crt
              subPath: ca.crt                      
            - name: vault-tls-certificates
              mountPath: /vault/tls/tls.crt
              subPath: tls.crt
            - name: vault-tls-certificates
              mountPath: /vault/tls/tls.key
              subPath: tls.key
          ports:
            - containerPort: 8200
            # - containerPort: 8201
          env:
            - name: VAULT_DISABLE_MLOCK
              value: "true"
            - name: VAULT_API_ADDR
              value: https://vault.{{.Values.domain}}:8200
          command: ["vault", "server", "-config", "/vault/config/config.json"]
      restartPolicy: Always
      volumes:
        - name: vault-json-config
          configMap:
            name: vault-cm
        - name: vault-tls-certificates
          secret:
            secretName: vault-cert-secret
---
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: {{.Release.Namespace}}
spec:
  selector:
    app: vault
  type: ClusterIP
  ports:
  - name: https
    port: 8200
    targetPort: 8200
    protocol: TCP
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: vault-ingress
#   namespace: {{.Release.Namespace}}
#   annotations: 
#     cert-manager.io/issuer: "lamassu-ca-issuer"
#     kubernetes.io/ingress.class: "nginx"
#     nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
# spec:
#   tls:
#   - hosts:
#     - vault.{{.Values.domain}}
#     secretName: downstream-crt-secret
#   rules:
#   - host: vault.{{.Values.domain}}
#     http: 
#       paths:
#       - pathType: Prefix
#         path: /
#         backend: 
#           service: 
#             name: "vault"
#             port:
#               number: 8200