{{- if .Values.services.keycloak.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: {{.Release.Namespace}}
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: {{.Values.services.keycloak.image}}
          imagePullPolicy: Always
          volumeMounts:          
            - name: auth-tls-certificates
              mountPath: /etc/x509/https/tls.crt
              subPath: tls.crt
            - name: auth-tls-certificates
              mountPath: /etc/x509/https/tls.key
              subPath: tls.key
          ports:
            - containerPort: 8080
            - containerPort: 8443
          env:
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: jdbc:postgresql://postgresql-pgpool/auth #Service Name for HA postgres
            - name: KC_DB_USERNAME
              value: {{.Values.postgresqlha.global.postgresql.username}}
            - name: KC_DB_PASSWORD
              value: {{.Values.postgresqlha.global.postgresql.password}}
            - name: KEYCLOAK_ADMIN
              value: {{.Values.services.keycloak.adminCreds.username}}
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: {{.Values.services.keycloak.adminCreds.password}}
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_PROXY
              value: reencrypt
            - name: KC_HTTP_RELATIVE_PATH
              value: /auth
            - name: KC_HOSTNAME_PATH
              value: /auth
            - name: HTTP_ADDRESS_FORWARDING
              value: "true"
            - name: QUARKUS_HTTP_ACCESS_LOG_ENABLED
              value: "true"
            # - name: QUARKUS_HTTP_ACCESS_LOG_PATTERN
            #   value: "%r\n%{ALL_REQUEST_HEADERS}"

      restartPolicy: Always
      volumes:
        - name: auth-tls-certificates
          secret:
            secretName: auth-upstream-cert
{{- end -}}