apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-cert
  namespace: {{.Release.Namespace}}
spec:
  isCA: false
  commonName: auth*
  duration: {{.Values.tls.duration}}
  dnsNames:
    - "auth"
    - "auth*"
  secretName: auth-upstream-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: upstream-ca-issuer
    kind: Issuer
    group: cert-manager.io