{{- if .Values.services.awsConnector.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aws-connector-identifier
  namespace: {{.Release.Namespace}}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{.Values.storageClassName}}
  resources:
    requests:
      storage: 1Mi
{{- end -}}
