apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: consul-cert
  namespace: {{.Release.Namespace}}
spec:
  isCA: false
  commonName: consul*
  duration: {{.Values.tls.duration}}
  # renewBefore: "55m"
  dnsNames:
    - "consul"
    - "consul-server" #Services use this 
    - "server.lamassu-k8s.consul" # Vault clustering useses this
    - "consul*"
  secretName: consul-upstream-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: upstream-ca-issuer
    kind: Issuer
    group: cert-manager.io