{{- if eq .Values.tls.type "selfSigned" -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: downstream-tls-certificate
  namespace: {{.Release.Namespace}}
spec:
  isCA: false
  commonName: {{.Values.domain}}
  duration: {{.Values.tls.duration}}
  dnsNames:
    - "{{.Values.domain}}"
    - "*.{{.Values.domain}}"
  secretName: downstream-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: downstream-ca-issuer
    kind: Issuer
    group: cert-manager.io
{{- end -}}
{{- if eq .Values.tls.type "letsEncrypt" -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: downstream-tls-certificate
  namespace: {{.Release.Namespace}}
spec:
  isCA: false
  commonName: {{.Values.domain}}
  duration: {{.Values.tls.duration}}
  dnsNames:
    - "{{.Values.domain}}"
    - "*.{{.Values.domain}}"
  secretName: downstream-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: letsencrypt-issuer
    {{if .Values.tls.letsEncryptOptions.clusterIssuer -}}
    kind: ClusterIssuer
    {{- end -}}
    {{if .Values.tls.letsEncryptOptions.issuer -}}
    kind: Issuer
    {{- end}}
    group: cert-manager.io
{{- end -}}