apiVersion: apps/v1
kind: Deployment
metadata:  
  name: ocsp
  namespace: {{.Release.Namespace}}
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: ocsp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocsp
  template:
    metadata:
      labels:
        app: ocsp
    spec:     
      containers:
        - name: ocsp
          image: {{.Values.services.ocsp.image}}
          imagePullPolicy: Always
          tty: true          
          env:
            - name: SERVICE_NAME
              value: ocsp
            - name: DEBUG_MODE
              value: "{{.Values.debugMode}}"
            - name: PORT
              value: "8085"
            - name: PROTOCOL
              value: https
            - name: CERT_FILE
              value: /certs/tls.crt
            - name: KEY_FILE
              value: /certs/tls.key
            - name: MUTUAL_TLS_ENABLED
              value: "true"
            - name: MUTUAL_TLS_CLIENT_CA
              value: /certs/internal-ca.crt
            - name: AMQP_SERVER_USE_BASIC_AUTH
              value: "true"
            - name: AMQP_SERVER_USERNAME
              value: "{{.Values.rabbitmq.auth.username}}"
            - name: AMQP_SERVER_PASSWORD
              value: "{{.Values.rabbitmq.auth.password}}"
            - name: AMQP_SERVER_ENABLE_TLS
              value: "true"
            - name: AMQP_SERVER_HOST
              value: rabbitmq
            - name: AMQP_SERVER_PORT
              value: "5671"
            - name: AMQP_SERVER_CA_CERT
              value: /certs/internal-ca.crt

            - name: LAMASSU_CA_ADDRESS
              value: https://ca:8085
            - name: LAMASSU_CA_CERT_FILE
              value: /certs/internal-ca.crt
            - name: SIGNER_CERT
              value: /certs/signer.crt
            - name: SIGNER_KEY
              value: /certs/signer.key

          volumeMounts:
            - name: downstream-certificates
              mountPath: /certs/signer.crt
              subPath: tls.crt
            - name: downstream-certificates
              mountPath: /certs/signer.key
              subPath: tls.key
            - name: tls-certificates
              mountPath: /certs/tls.crt
              subPath: tls.crt
            - name: tls-certificates
              mountPath: /certs/tls.key
              subPath: tls.key
            - name: tls-certificates
              mountPath: /certs/internal-ca.crt
              subPath: ca.crt
          ports:
            - containerPort: 8085
      restartPolicy: Always
      volumes:
        - name: tls-certificates
          secret:
            secretName: ocsp-upstream-cert
        - name: downstream-certificates
          secret:
            secretName: {{ template "downstream.certSecret" . }}