apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ocsp-cert
  namespace: {{.Release.Namespace}}
spec:
  isCA: false
  commonName: ocsp*
  dnsNames:
    - "ocsp"
    - "ocsp*"
  secretName: ocsp-upstream-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: upstream-ca-issuer
    kind: Issuer
    group: cert-manager.io