kind: ConfigMap
apiVersion: v1
metadata:
  name: opa-server-config-cm
  namespace: {{.Release.Namespace}}
data:
  config.yaml: |
    plugins:
      envoy_ext_authz_grpc:
        addr: :9191
        path: lamassu/gateway/security/allow
    services:
      rem_logger:
        url: http://localhost:8080
    decision_logs:
      # console: true
      service: rem_logger
    status:
      console: true