apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ui-cert
  namespace: {{.Release.Namespace}}
spec:
  isCA: false
  commonName: ui*
  dnsNames:
    - "ui"
    - "ui*"
  secretName: ui-upstream-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: upstream-ca-issuer
    kind: Issuer
    group: cert-manager.io