apiVersion: apps/v1
kind: Deployment
metadata:  
  name: ui
  namespace: {{.Release.Namespace}}
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:     
      containers:
        - name: ui
          image: {{.Values.services.ui.image}}
          imagePullPolicy: Always
          env:
            - name: DOMAIN
              value: {{.Values.domain}}
            - name: REACT_APP_AUTH_ENDPOINT
              value: "https://auth.{{.Values.domain}}/auth"
            - name: REACT_APP_AUTH_REALM
              value: "lamassu"
            - name: REACT_APP_AUTH_CLIENT_ID
              value: "frontend"
            - name: REACT_APP_LAMASSU_CLOUD_PROXY_API
              value: "https://{{.Values.domain}}/api/cloudproxy"
            - name: REACT_APP_LAMASSU_CA_API
              value: "https://{{.Values.domain}}/api/ca"
            - name: REACT_APP_LAMASSU_DMS_ENROLLER_API
              value: "https://{{.Values.domain}}/api/dmsenroller"
            - name: REACT_APP_LAMASSU_DEVMANAGER
              value: "https://{{.Values.domain}}/api/devmanager"
          volumeMounts:
            - name: ui-tls-certificates
              mountPath: /certs/tls.crt
              subPath: tls.crt
            - name: ui-tls-certificates
              mountPath: /certs/tls.key
              subPath: tls.key
          ports:
            - containerPort: 443
      restartPolicy: Always
      volumes:
        - name: ui-tls-certificates
          secret:
            secretName: ui-upstream-cert