{{- if .Values.simulationTools.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:  
  name: virtual-device
  namespace: {{.Release.Namespace}}
  labels:
    app: virtual-device
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virtual-device
  template:
    metadata:
      labels:
        app: virtual-device
    spec:
      containers:
        - name: virtual-device
          image: {{.Values.simulationTools.virtualDevice.image}}
          imagePullPolicy: Always
          tty: true      
          env:
            - name: VDMS_ADDRESS
              value: http://virtual-dms:7002
            - name: LAMASSU_GATEWAY 
              value: https://{{.Values.domain}}
            - name: AWS_IOT_ENDPOINT 
              value: "a"
            - name: AWS_IOT_CA
              value: /app/aws-iotcore-ca.crt
            - name: AZURE_IOT_HUB_ENDPOINT 
              value: "a"
            - name: AZURE_DPS_ENDPOINT 
              value: "a"
            - name: AZURE_SCOPE_ID 
              value: "a"
            - name: AZURE_IOT_HUB_CA 
              value: "/app/azure-iothub-ca.crt"
            - name: OPERATOR_USERNAME 
              value: "enroller"
            - name: OPERATOR_PASSWORD 
              value: "enroller"
            - name: DOWNSTREAM_CERT 
              value: "/certs/downstream.crt"
            - name: DMS_NAME 
              value: "HostCloudDMS"
            - name: HOST_CLOUD_DMS 
              value: "true"
            - name: BOOTSTRAP_CA_NAME
              value: BootstrapCA1
          volumeMounts:
            - name: downstream-tls-certificates
              mountPath: /certs/downstream.crt
              subPath: tls.crt
          ports:
            - containerPort: 7001
      restartPolicy: Always
      volumes:
        - name: downstream-tls-certificates
          secret:
            secretName: downstream-cert
{{- end -}}
