name: Main Workflow

on:
  push:
    paths:
      - ci/auth/**
      - ci/toolbox/**
    branches:
      - develop

env:
  DOCKER_IMAGE_PREFIX: ghcr.io/lamassuiot

jobs:
  build_auxiliar_compose_release:
    name: Build Auxilar Services
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Login to Github Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Keycloak Docker image
        uses: docker/build-push-action@v2
        with:
          context: config/auth
          push: true
          tags: |
            $DOCKER_IMAGE_PREFIX/keycloak:${{ github.sha }}
            $DOCKER_IMAGE_PREFIX/keycloak:dev

      - name: Build Toolbox Docker image
        uses: docker/build-push-action@v2
        with:
          context: config/toolbox
          push: true
          tags: |
            $DOCKER_IMAGE_PREFIX/toolbox:${{ github.sha }}
            $DOCKER_IMAGE_PREFIX/toolbox:dev