name: Main Workflow

on:
  push:
    paths:
      - ci/auth/**
      - ci/toolbox/**
    branches:
      - develop

env:
  DOCKER_IMAGE_PREFIX: ghcr.io/lamassuiot/lms

jobs:
  build_auxiliar_compose_release:
    name: Build Auxilar Services
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build Keycloak Docker image
        uses: docker/build-push-action@v2
        with:
          context: config/auth
          push: true
          tags: |
            $DOCKER_IMAGE_PREFIX-auth-dev:${{ github.sha }}
            $DOCKER_IMAGE_PREFIX-auth-dev:latest

      - name: Build Toolbox Docker image
        uses: docker/build-push-action@v2
        with:
          context: config/toolbox
          push: true
          tags: |
            $DOCKER_IMAGE_PREFIX-toolbox-dev:${{ github.sha }}
            $DOCKER_IMAGE_PREFIX-toolbox-dev:latest